### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid TeamProgression

### ISSUE THREAD

**Issue by czakiss** [frengor/UltimateAdvancementAPI#25]
**Describe the bug**

Throws `java.lang.IllegalArgumentException: Invalid TeamProgression` on UltimateAdvancementAPI plugin while use method `api.updatePlayerTeam(player, playerOwner)`

**To Reproduce**
```java
advancementTabGlob.getEventManager().register(new Object(), PlayerLoadingCompletedEvent.class, playerLoadingCompletedEvent -> {
            Player player = playerLoadingCompletedEvent.getPlayer();
            ultimateAdvancementAPI.movePlayerInNewTeam(player);
            Player owner = Bukkit.getPlayer("Czakiss");
            if (owner != null && !owner.equals(player)){
                Bukkit.getLogger().info("This player is not owner");
                ultimateAdvancementAPI.updatePlayerTeam(player,owner);
            }
            ultimateAdvancementAPI.updatePlayer(player);
            loadPlayerToTeam(player);
        });
```

**System, Java, Server and Plugin Version**
System: Windows 11
Java:  Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
Server: git-Purpur-1611 (MC: 1.18.2) --- ( clone paperspigot )
Plugin: UltimateAdvancementAPI (2.1.3)

**Screenshots**
![image](https://user-images.githubusercontent.com/40041307/166809479-e463fa32-c0a6-445c-8c77-3c650c32a258.png)

**Comment by ipiepiepie** [comment]
I think it still broken, cause I'm faced with this problem on the latest plugin version (2.2.0)
![image](https://user-images.githubusercontent.com/67694341/176335658-04aba0e2-8744-4c0d-a1fe-81f2582349aa.png)
