### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid TeamProgression exception

### ISSUE THREAD

**Issue by ipiepiepie** [frengor/UltimateAdvancementAPI#28]
**Describe the bug**
Throws `java.lang.IllegalArgumentException: Invalid TeamProgression` on UltimateAdvancementAPI plugin while use method `api.updatePlayerTeam(player, playerOwner)`
> There is already this issue here (#25), but it closed and I think that file new issue better, than comment closed one.

**To Reproduce**
Just use `api.updatePlayerTeam(player, playerOwner)`, method something like that:
```Java
@EventHandler
public void onResidentJoinTown(TownAddResidentEvent event) { 
    Resident resident = event.getResident();
    Plugin.getAdvancementsAPI().updatePlayerTeam(resident.getUUID(), event.getTown().getMayor().getUUID());
    if (resident.isOnline() && resident.getPlayer() != null) {
        Plugin.getAdvancementsAPI().updatePlayer(resident.getPlayer());
        PluginAPI.getInstance().getAdvancementTab().showTab(resident.getPlayer());
    }
}
```
**System, Java, Server and Plugin Version**
System: Windows 10
Java: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12-39)
Server: Paper version git-Paper-794 (MC: 1.16.5)
Plugin: UltimateAdvancementAPI (2.2.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/67694341/176424663-39e8e529-20a6-4d9c-9b57-10477e3db441.png)

**Comment by frengor** [comment]
This may be due to a race condition: `movePlayerInNewTeam` is done async and as soon as the update is finished the cache is updated, so perhaps calling `updatePlayer` may try to update the not updated team.
Can you try to move the updatePlayer into the callback (see [movePlayerInNewTeam(Player player, Consumer callback)](https://frengor.com/javadocs/UltimateAdvancementAPI/2.2.0/com/fren_gor/ultimateAdvancementAPI/UltimateAdvancementAPI.html#movePlayerInNewTeam(org.bukkit.entity.Player,java.util.function.Consumer)))?

> Also, the `updatePlayer` call isn't really needed here since `movePlayerInNewTeam` already updates players

**Comment by ipiepiepie** [comment]
> This may be due to a race condition: `movePlayerInNewTeam` is done async and as soon as the update is finished the cache is updated, so perhaps calling `updatePlayer` may try to update the not updated team. Can you try to move the updatePlayer into the callback (see [movePlayerInNewTeam(Player player, Consumer callback)](https://frengor.com/javadocs/UltimateAdvancementAPI/2.2.0/com/fren_gor/ultimateAdvancementAPI/UltimateAdvancementAPI.html#movePlayerInNewTeam(org.bukkit.entity.Player,java.util.function.Consumer)))?
> 
> > Also, the `updatePlayer` call isn't really needed here since `movePlayerInNewTeam` already updates players

Aww sorry, I'm just realised, that I linked wrong code in issue.

My code is:
```Java
    @EventHandler
    public void onResidentJoinTown(TownAddResidentEvent event) {
        Resident resident = event.getResident();
        ResearchPlugin.getAdvancementsAPI().updatePlayerTeam(resident.getUUID(), event.getTown().getMayor().getUUID());

        if (resident.isOnline() && resident.getPlayer() != null) {
            ResearchPlugin.getAdvancementsAPI().updatePlayer(resident.getPlayer());
            ResearchAPI.getInstance().getAdvancementTab().showTab(resident.getPlayer());
        }
    }
```

Here I'm trying to create one team for all residents of town in Towny plugin, so I decided to add new town residents to mayor's team, but it causes exception, that you can see on my screenshot above

**Comment by frengor** [comment]
Try to remove this line then
```java
Plugin.getAdvancementsAPI().updatePlayer(resident.getPlayer());
```
(since `updatePlayerTeam` already updates players)

**Comment by ipiepiepie** [comment]
Still doesn't work.
I thought that `Resident#getUUID()` returns wrong UUID, so I'm tried to use `Resident#getPlayer()`, to make sure that UUID belongs to bukkit player, but it didn't give any results..

**Comment by EscanorTargaryen** [comment]
Sorry for the delay, we are aware of the problem and will fix it in the next versions. Unfortunately, however, between university studies and travel/holidays we have not had time. We care a lot about our api and are sorry that one of our features is currently unusable.

**Comment by ipiepiepie** [comment]
> Sorry for the delay, we are aware of the problem and will fix it in the next versions. Unfortunately, however, between university studies and travel/holidays we have not had time. We care a lot about our api and are sorry that one of our features is currently unusable.

My plugin really needs this feature, so hope it will be fixed as soon as possible

**Comment by EscanorTargaryen** [comment]
Hi, we have been testing the problem and we have a solution!
We realized that mainly this problem occurs on Paper and can be solved by waiting for the database and cache to be updated after moving a player from one team to another.
So there are 2 ways:
- If you don't have to do anything after moving the player to another team, just run [#updatePlayerTeam()](https://frengor.com/javadocs/UltimateAdvancementAPI/2.2.0/com/fren_gor/ultimateAdvancementAPI/UltimateAdvancementAPI.html#updatePlayerTeam(java.util.UUID,java.util.UUID)) and that's it (meaning don't run anything after that line of code).
- If after moving the player to another team you need to execute more code with our API, use its thread-safe version (see [updatePlayerTeam(UUID playerToMove, UUID aDestTeamPlayer, Consumer callback)](https://frengor.com/javadocs/UltimateAdvancementAPI/2.2.0/com/fren_gor/ultimateAdvancementAPI/UltimateAdvancementAPI.html#updatePlayerTeam(java.util.UUID,java.util.UUID,java.util.function.Consumer))) which we actually already recommended you use. Simply the callback is called when everything has been updated correctly and you can run all the code you want.

Small example with your code
```java
@EventHandler
public void onResidentJoinTown(TownAddResidentEvent event) { 
    Resident resident = event.getResident();
    Plugin.getAdvancementsAPI().updatePlayerTeam(resident.getUUID(), event.getTown().getMayor().getUUID(), c -> {
        if (resident.isOnline() && resident.getPlayer() != null) {
            Plugin.getAdvancementsAPI().updatePlayer(resident.getPlayer());
            PluginAPI.getInstance().getAdvancementTab().showTab(resident.getPlayer());
        }
    });
}
```

We hope this will solve your problem and look forward to your feedback.

**Comment by ipiepiepie** [comment]
Yeah! Thats works, thank you!
