### ISSUE TITLE
Tab completion for `/uladv grant one ..` crashes server

### ISSUE THREAD

**Issue by ipiepiepie** [frengor/UltimateAdvancementAPI#29]
**Describe the bug**
Server crushes when I'm use `/uladv grant one` command. I think it happend because of incorrect tab completion work

**To Reproduce**
Write `/uladv grant one` and click space button. Server will lag to 1-2 seconds and then crash.

**System, Java, Server and Plugin Version**
System: Windows 10
Java: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12-39)
Server: Paper version git-Paper-794 (MC: 1.16.5)
Plugin: UltimateAdvancementAPI (2.2.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/67694341/177017145-757f089a-71dc-49e7-b7b3-afe6eafd7780.png)

**Comment by frengor** [comment]
It's a CommandAPI bug: https://github.com/JorelAli/CommandAPI/issues/297
