### ISSUE TITLE
API not work with offline mode server

### ISSUE THREAD

**Issue by Xen0Xys** [frengor/UltimateAdvancementAPI#31]
I foud out that the UltimateAdvancementAPI is not working when the server is on offline mode

You can see in the first picture that the advancement is granted, but in the advancement tab there is no advancements (the root advancement is normally grant automaticly but there is nothing on the chat about it):

![Screenshot_1](https://user-images.githubusercontent.com/47594493/196270799-0eef444d-11da-4514-9443-91131111b909.png)
![Screenshot_2](https://user-images.githubusercontent.com/47594493/196270796-ac291230-70cd-4d72-b13a-c07bcf3051cc.png)
![Screenshot_3](https://user-images.githubusercontent.com/47594493/196270789-3dafb633-e2b9-41dc-81a3-8fb5e985fde7.png)

Thanks for your help!

**Comment by frengor** [comment]
You have to listen to the `PlayerLoadingCompletedEvent` instead of `PlayerJoinEvent`, so your code will be:
```java
@EventHandler
public void onPlayerLoading(PlayerLoadingCompletedEvent e) {
    advancementManager.getBaseAdvancement("temp").grant(e.getPlayer());
}
```

Also, whether the server is in online or offline mode should not matter at all.

**Comment by Xen0Xys** [comment]
So your change didn't change anything for me, but I found out something:
When the world is created online and I connect myself, I got the advancements without any problems
After that, if I put the server on offline mode, and connect myself with the same username, something is causing troubles with the advancement grant.

So at this point my problem is solved, thanks for your help!

**Comment by frengor** [comment]
It feels like there's some kind of server bug. Are there any errors in the console? What server software are you using?

**Comment by Xen0Xys** [comment]
No errors, I used paper-1.19.2-177 for my tests
