### ISSUE TITLE
Invalid link in wiki: Configuration page (for server owners)

### ISSUE THREAD

**Issue by VladOliinyk** [frengor/UltimateAdvancementAPI#33]
On [this](https://github.com/frengor/UltimateAdvancementAPI/wiki/) page the paragraph that relates the reader to the [installation page](https://github.com/frengor/UltimateAdvancementAPI/wiki/Installation) and [configuration page](https://github.com/frengor/UltimateAdvancementAPI/wiki/.Configuration) contain invalid **Configuration** link.

There are: https://github.com/frengor/UltimateAdvancementAPI/wiki/.Configuration
But should be: https://github.com/frengor/UltimateAdvancementAPI/wiki/Configuration
So no . (dot) before the "Configuration" word.

Thanks <3

**Comment by EscanorTargaryen** [comment]
Fixed, thanks for the report!
