### ISSUE TITLE
defaultColor in the constructor of AdvancementDisplay doesn't work

### ISSUE THREAD

**Issue by D-Hydrogen** [frengor/UltimateAdvancementAPI#36]
When I put a ChatColor object into the constructor
`public AdvancementDispay(icon, title, frame, showToast, announceChat, x, y, defaultCOlor, description)`
there isn't any effect and the color doesn't change.
For some reason I have to use 1.19.3paper, is that the cause?
thanks.

**Comment by EscanorTargaryen** [comment]
Hi, could you show us some screenshots of what is happening and the code you are using?

**Comment by frengor** [comment]
Closing since we cannot reproduce the bug
