### ISSUE TITLE
Online generator Save

### ISSUE THREAD

**Issue by SirC4LV1N** [frengor/UltimateAdvancementAPI#39]
Sometimes the online generator does not save the changes correctly  and reverse them at a refresh and re-login in google drive

After pressing Save:
![image](https://user-images.githubusercontent.com/106480423/224384964-5186aefe-eb43-41f5-bc06-0e58a8c09fb7.png)

At refresh and re-login into google:
![image](https://user-images.githubusercontent.com/106480423/224385421-b748f936-0403-40a9-9c1a-fe2a93c975bd.png)

**Comment by EscanorTargaryen** [comment]
Hi, could you let me know what browser you are using? Do you have errors in console when it doesn't save data?

**Comment by SirC4LV1N** [comment]
Im using google chrome, and yes i got two erros:
![image](https://user-images.githubusercontent.com/106480423/224403383-31ac9f36-d6ac-426a-bb04-fbd7b2335495.png)

**Comment by EscanorTargaryen** [comment]
Could you paste the entire log of the errors?

**Comment by SirC4LV1N** [comment]
[generator.escanortargaryen.ga-1678475154947.log](https://github.com/frengor/UltimateAdvancementAPI/files/10945162/generator.escanortargaryen.ga-1678475154947.log)

**Comment by EscanorTargaryen** [comment]
Ok thanks for reporting, i will try to fix it. Last thing, could you test if changing your connection or using a vpn can help to solve your issue?

**Comment by SirC4LV1N** [comment]
Using a VPN does not seem to work. 
And i only have my home wlan, nothing else D:

**Comment by SirC4LV1N** [comment]
I dont know it it helps, but i dug thru the logs and found this:

![image](https://user-images.githubusercontent.com/106480423/224475080-88f6162c-7b4d-4546-b3f1-8f0f8c7dcab4.png)

**Comment by EscanorTargaryen** [comment]
I think that's the error I needed! Anyway at the generator I work on it in my spare time, don't expect an immediate fix 😅 (just so you know)

**Comment by EscanorTargaryen** [comment]
I think that's the error I needed! Anyway I work on generator in my spare time, don't expect an immediate fix 😅 (just so you know)

**Comment by EscanorTargaryen** [comment]
I should have solved it!
