### ISSUE TITLE
Advancement key not updating properly in online generator

### ISSUE THREAD

**Issue by JoloJanssen** [frengor/UltimateAdvancementAPI#48]
When you make an advancement and give it a child advancement and after that change the Advancementkey of the parent, the code provided by the online generator only updates half. The new Advancementkey is saved as under the correct variable, but is not carried over to the corresponding "parent" input of the child.

![afbeelding_2023-06-21_170920777](https://github.com/frengor/UltimateAdvancementAPI/assets/74826171/0f76ee9a-af49-4e36-8b6a-9aed39fa046c)

Image: These advancements should chain together, but the parent name i not updated in the child creation lines
In this example "oak_sapling90" is supposed to be "elemental_magic1".

**Comment by EscanorTargaryen** [comment]
Thanks for the report, it is a very simple problem to solve, I will do it in the next few days.

**Comment by EscanorTargaryen** [comment]
The problem only occurred with the RootAdvancement, I should have fixed it. Recreate the RootAdvancement and its children from the generator, then it should work.

**Comment by JoloJanssen** [comment]
I fixed it manually. By setting the parent to something else and back to what its supposed to be it will copy the correct AdvancementKey. Having said that, it didn't occur with just the root advancement, since the image i showed are 3-7 deep in the tree (root=1 here). I will update the issue if I can still reproduce it, but will consider it solved for now.
