### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by rudde0** [frengor/UltimateAdvancementAPI#49]
Could you add support for MC 1.20.2?

**Comment by frengor** [comment]
*Copied from [FAQ](https://github.com/frengor/UltimateAdvancementAPI/wiki/FAQ#a-new-minecraft-version-just-come-out-when-will-ultimateadvancementapi-be-ready-for-the-new-version):*  
We try to publish the update as soon as possible, however it could happen that a release gets delayed a bit. We are currently attending university and we're working on the API in our free time.

Also, UltimateAdvancementAPI can't be updated until all of its dependency are updated too (mainly [CommandAPI](https://github.com/JorelAli/CommandAPI), they are usually quick with the updates though).

---

To be more specific, at the moment we are waiting for the CommandAPI update.

**Comment by rudde0** [comment]
Thanks for explanation. :)

CommandAPI just updated for MC 1.20.2.

**Comment by frengor** [comment]
Updated!
