### ISSUE TITLE
1.20.2 - displayCustomToast not working

### ISSUE THREAD

**Issue by envizar** [frengor/UltimateAdvancementAPI#51]
Well, `displayCustomToast` is only thing I need from UltimateAdvancementAPI...
But somewhy it's not working on lastest 1.20.2 Paper

**Comment by EscanorTargaryen** [comment]
Hi! Could you tell us if there are any errors in the console?

**Comment by envizar** [comment]
No, custom toast just not appearing

**Comment by EscanorTargaryen** [comment]
Can you make sure the api is loaded correctly, for example if you can do the `/ultimateadvancementapi grant all` command without any problem

**Comment by envizar** [comment]
![изображение](https://github.com/frengor/UltimateAdvancementAPI/assets/87126318/20b6ae63-bd5b-4a8c-a9b8-65e3edb1a862)

**Comment by envizar** [comment]
This issue related to ViaFabricPlus or ViaVersion, on 1.20.2 vanilla it works
