### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by mrjasonn** [frengor/UltimateAdvancementAPI#56]
Please do as there are people including me waiting for you to update

**Comment by EscanorTargaryen** [comment]
We have to wait for CommandAPI update

**Comment by JorelAli** [comment]
CommandAPI 9.3.0 has been released which adds support for Minecraft 1.20.3 and 1.20.4.

**Comment by frengor** [comment]
Version 2.2.8 supports 1.20.3 and 1.20.4.
