### ISSUE TITLE
Incorrect annotation on AdvancementKey constructor

### ISSUE THREAD

**Issue by Fusezion** [frengor/UltimateAdvancementAPI#60]
When creating a new advancement key from a namespaced key, the annotation is marked as `@Nullable` when internally you're expecting an `@NotNull`
https://github.com/frengor/UltimateAdvancementAPI/blob/6b7a32660958df6a857afc2972558e982031c36b/Common/src/main/java/com/fren_gor/ultimateAdvancementAPI/util/AdvancementKey.java#L69-L76

**Comment by frengor** [comment]
Good catch, thank you! We'll fix it in the next release. (we also accept contributions, if you'd like to contribute just make sure to contribute to the `dev` branch)
