### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by mrjasonn** [frengor/UltimateAdvancementAPI#61]
Please do as there are people including me waiting for you to update

**Comment by EscanorTargaryen** [comment]
https://github.com/frengor/UltimateAdvancementAPI/wiki/FAQ#a-new-minecraft-version-just-come-out-when-will-ultimateadvancementapi-be-ready-for-the-new-version

**Comment by frengor** [comment]
Version 2.3.0 supports 1.20.5 and 1.20.6.
