### ISSUE TITLE
Feature Request: Allow negative advancement coordinates

### ISSUE THREAD

**Issue by GavvyDizzle** [frengor/UltimateAdvancementAPI#66]
When designing advancement pages, I find it easier to center my advancements on the Y axis and place other advancements above/below that line. 

The API doesn't allow negative coordinates, but there should be a relatively easy solution. For an advancement tab you know all of the coordinates when registering them. Just add the minX and minY values (if negative) to all advancements to keep them positive.

**Comment by EscanorTargaryen** [comment]
Hi! There is already a solution for negative co-ordinates.
As cited in the wiki [AdvancementDisplay](https://github.com/frengor/UltimateAdvancementAPI/wiki/AdvancementDisplay#advancement-coordinates):

> UltimateAdvancementAPI supports negative coordinates since 2.1.0 through the [CoordAdapter class](https://frengor.com/javadocs/UltimateAdvancementAPI/latest/com/fren_gor/ultimateAdvancementAPI/util/CoordAdapter.html).

Where you can find an example about it.
