### ISSUE TITLE
Update Request: 1.21.1

### ISSUE THREAD

**Issue by cobrex1** [frengor/UltimateAdvancementAPI#70]
Could you update the plugin for 1.21.1 please as it does not enable on this server version.
Thanks

**Comment by EscanorTargaryen** [comment]
Hello, I'm sorry, could you give us a few more days bacause we are on holiday

**Comment by cobrex1** [comment]
Of course, I apologise for disturbing you while you are on holiday.

**Comment by frengor** [comment]
Version 2.4.1 adds support for Minacraft 1.21.1
