### ISSUE TITLE
com.fren_gor don't exist

### ISSUE THREAD

**Issue by MathiasDPX** [frengor/UltimateAdvancementAPI#74]
![image](https://github.com/user-attachments/assets/24e0882b-6976-48aa-873c-4ba0704f9492)

What I added in build.gradle:
```groovy
compileOnly 'com.frengor:ultimateadvancementapi:2.4.1'
maven { url = "https://nexus.frengor.com/repository/public/" }
```

I tried to add UltimateAdvancementAPI to my plugin but I don't find com.fren_gor
[Plugin is opensource](https://github.com/ServerOpenMC/Plugin)

It build correctly without errors*

**Comment by frengor** [comment]
I can see you have JitPack declared in your maven repos. Try putting `maven { url = "https://nexus.frengor.com/repository/public/" }` before JitPack.

**Comment by MathiasDPX** [comment]
Same issue
```groovy
repositories {
    mavenCentral()
    mavenLocal()
    maven { url = "https://repo.purpurmc.org/snapshots" }
    maven { url = "https://mvn.coolcraft.ovh/releases" }
    maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url = 'https://maven.enginehub.org/repo/' }
    maven { url = "https://repo.onarandombox.com/content/groups/public/" }
    maven { url = "https://nexus.frengor.com/repository/public/" }
    maven { url = "https://jitpack.io" }
}
```

**Comment by MathiasDPX** [comment]
![image](https://github.com/user-attachments/assets/9c0fed3d-d11b-45cd-88d9-4ecd5fa2b10e)
ultimateadvancementapi is first in dependancies

**Comment by frengor** [comment]
It's probably IntelliJ, try using the File > Repair IDE button.

**Comment by MathiasDPX** [comment]
That's weird,
I had to delete the whole project and clone it again

Sorry for bothering you

**Comment by MathiasDPX** [comment]
It was because nexus.frengor.com was after mavenLocal()
